LC29: add Session type
1904labs/labs-chat pull request #16
Opened 2024-06-07 16:56 UTC by jcm5155

2024-06-07 20:01 UTC, NAPTlME requested changes

2024-06-07 20:01 UTC, NAPTlME commented on frontend/labs-chat/src/helpers/memory.js
@jcm5155 
Could we remove this change to the Memory class for now.

2024-06-07 21:05 UTC, NAPTlME approved these changes

2024-06-10 15:53 UTC, superjkm approved these changes

2024-06-10 15:54 UTC, merged